### ISSUE TITLE
When (some?) transform are applied, dataset __getitem__ returns tuple

### ISSUE THREAD

**Issue by neworderofjamie** [neuromorphs/tonic#121]
If I add a transform:
```python
subsample_transform = tonic.transforms.Subsample(1e-3)
dataset = tonic.datasets.SHD(save_to='./data', train=False, transform=subsample_transform)
events, label = dataset[0]
```
events is now a tuple with a superfluous ``None``. This is really annoying so I'm more than happy to fix this in tonic rather than my code but, I'm not quite sure _why_ transform classes are returning ``images`` at all (e.g. [here](https://github.com/neuromorphs/tonic/blob/develop/tonic/transforms.py#L314)) so not totally clear how to fix it. Would the correct fix be to duplicate [this logic](https://github.com/neuromorphs/tonic/blob/develop/tonic/transforms.py#L29-L32) from ``transform.Compose`` across all transforms (the 'functional' transforms just seem to return events).

**Comment by biphasic** [comment]
Hey Jamie, the way Tonic is designed is that the transforms.Compose wrapper is always necessary, even with a single transform as indicated [here](https://tonic.readthedocs.io/en/latest/transformations.html#tonic.transforms.Compose). I modeled it after Pytorch vision and also newer augmentation frameworks do it [like that](https://github.com/facebookresearch/AugLy/tree/main/augly/image). I understand that it's counterintuitive when using a single transform. The problem is that, even if you replicated the logic you referenced for all transforms, how would you stack them if you don't know what each of them returns?

**Comment by biphasic** [comment]
the reason why the transform classes return images is so that they can get pulled through the chain of transformations, and some classes make use of the images, and some don't. We could make a case to get rid of image transforms all together, as only cropping and flipping and time reversal affects them. Some people do want to use the frames from let's say a DAVIS, so the original idea was to apply the same transforms to events and frames where possible. Maybe that's not needed and users can do it separately themselves

**Comment by neworderofjamie** [comment]
Ahh, good to know. If you _always_ need to use compose though, why not just take a list of transforms and automatically do the composing? (probably in a helper function to avoid duplicating across all datasets)

**Comment by biphasic** [comment]
also a good point! I'll give this some thought and try it out

**Comment by biphasic** [comment]
we're now fully compatible with Pytorch vision, so going to leave this as is for the moment.
