### ISSUE TITLE
Introduce option to disable verification

### ISSUE THREAD

**Issue by Tobias-Fischer** [neuromorphs/tonic#127]
At the moment the datasets are always verified, even if `download=False`. Hashing huge files takes quite a while though, and being able to skip the verification would be great.

**Comment by biphasic** [comment]
I agree and this relates to issue https://github.com/neuromorphs/tonic/issues/120. Will just disable file verification on `download=False`.

**Comment by biphasic** [comment]
fixed in commit d2ff9c57d1d9561efec740fea665ce5c00e260dd

starting from Tonic version 1.0, the `download` parameter has been removed from all datasets. When previously we did slow hashing of files to verify strict file integrity, this is now only done once after the download is completed. The next time the same dataset is instantiated, only lightweight checks are going to be run to check if the right filenames and number of files are present. This considerably speeds up training scripts overall.
Release will happen next week.
