### ISSUE TITLE
plotting a recording of NCALTECH using the utils function gives inconsistent results in terms of sensor size

### ISSUE THREAD

**Issue by biphasic** [neuromorphs/tonic#95]
<img width="388" alt="signal-2021-03-30-202358_002" src="https://user-images.githubusercontent.com/11279568/113041376-2f54a680-919a-11eb-9ca8-0faa879994f0.png">

**Comment by gcohen** [comment]
The recordings in N-Caltech101 are all different sizes, and it seems like you are setting sensor_size to (233, 173) in datasets/ncaltech101.py. Unfortunately, this would need to be set individually for each recording in that dataset. If I remember correctly, the original Caltech101 images are all different sizes, ad the recordings were resized in order to remove hard edges for images smaller that a fixed field of view.

This might require a slightly larger change to way the code functions, as the events in N-Caltech101 have different ranges of x and y. An easy fix may be for the plotting function (plot_events) to determine the range of x and y from the event-list passed to it, instead of using sensor_size. I'd suggest doing this only when sensor_size is set to None, and then explicitly setting sensor_size to None for N-Caltech101 in ncaltech101.py.

**Comment by biphasic** [comment]
Thanks a lot Greg! That is very helpful. I like your suggestion for a fix as well, I think that will work. I will look into that!

**Comment by biphasic** [comment]
fixed with new plotting function that automatically detects sensor_size, also fixed for N-Caltech101
https://github.com/neuromorphs/tonic/blob/edac681fd58882fb840d1c5dd1a5dcf574263cdc/tonic/utils.py#L7
https://github.com/neuromorphs/tonic/blob/edac681fd58882fb840d1c5dd1a5dcf574263cdc/tonic/datasets/ncaltech101.py#L68
